[FIX] account_ux: After web_notify dependencies module now it's installed automatically, and since there cold be not any default taxes, this is failing on res.config.settings execute trying to iterate over None object
```python
for other, data in pycompat.izip(others, data_list)
File "/root/odoo-12.0/odoo/fields.py", line 2769, in create
rel_ids[record.id].update(act[2])
TypeError: 'NoneType' object is not iterable
```