Cherry pick of e12181232e832d4be4c78fd6138c33ef3de4858b failed
stdout:
Auto-merging account_interests/views/res_company_views.xml
Auto-merging account_interests/models/res_company_interest.py
Auto-merging account_interests/__manifest__.py
CONFLICT (content): Merge conflict in account_interests/__manifest__.py

stderr:
10:41:54.010297 git.c:444               trace: built-in: git cherry-pick e12181232e832d4be4c78fd6138c33ef3de4858b
error: could not apply e1218123... [ADD] account_interests: late payment interest feature
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status: